config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  get "short_code_resolver/resolve/:collection_code/:work_code" => "short_code_resolver#resolve"
  get "application_status" => "status#application_status"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :custom_report_templates
  get "tags.json" => "application#tags"
  get "geoname_summaries.json" => "application#geoname_summaries"

  resources :reminders
  resources :stages
  get "offline/work_form"

  get "offline/offline"

  get "offline/collections"

  get "offline/collection"

  get "scan" => "scan#show"

  namespace :api do
    namespace :v1 do
      resources :time_spans, only: [:index, :show]
      resources :works, only: [:show]
      resources :work_sets, only: [:show]
      resources :collections, only: [:index, :show] do
        resources :works, only: [:index, :show] do
          resources :work_events, only: [:create]
        end
      end
    end
  end

  resources :messages do
    get "new_reply" => "messages#new"
  end
  devise_for :users, controllers: {
    confirmation: "confirmation",
    registrations: "registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }
  resources :users, only: [:index, :edit, :update, :destroy]
  get "users/oauth"

  resources :conditions
  resources :currencies
  resources :damage_types
  resources :frame_damage_types
  resources :frame_types
  resources :media
  resources :object_categories
  resources :logistical_peculiarities
  resources :placeabilities
  resources :sources
  resources :subsets
  resources :techniques
  resources :themes
  resources :balance_categories
  resources :work_statuses
  resources :work_sets, only: [:show, :index] do
    resources :works, module: :work_sets, only: :destroy # , controller: "WorkSet::WorksController"
  end
  resources :work_set_types

  resources :rkd_artists, module: :r_k_d, controller: :artists do
    patch "copy" => "rkd_artists#copy"
  end

  resources :works do
    resources :attachments
  end

  resources :involvements
  resources :collections do
    get "manage" => "collections#manage"
    get "manage/surface_tool" => "collections#surface_tool"
    resources :contacts
    resources :locations
    resources :users, module: :collection
    resources :labels, module: :collection
    resources :library_items
    resources :time_spans, only: [:index, :show]

    resources :work_sets do
      resources :appraisals
      resources :time_spans
    end

    resources :reminders, path: "manage/reminders"
    resources :themes, path: "manage/themes"
    resources :clusters
    resources :import_collections, path: "manage/import_collections" do
      get "preview" => "import_collections#preview"
      patch "delete_works" => "import_collections#delete_works"
      patch "import_works" => "import_collections#import_works"
    end

    resources :simple_import_collections, path: "manage/simple_import_collections" do
      get "preview" => "simple_import_collections#preview"
      patch "import_works" => "simple_import_collections#import_works"
    end

    resources :owners
    resources :custom_reports, path: "manage/custom_reports"

    resources :attachments
    resources :collections_stages
    resources :messages
    post "refresh_works" => "collections#refresh_works"
    resources :collections do
    end
    resources :batch_photo_uploads do
      post "match_works" => "batch_photo_uploads#match_works"
    end
    resources :artists do
      get :collectie_nederland_summary

      get "combine_prepare" => "artists#combine_prepare"
      patch "combine" => "artists#combine"

      resources :rkd_artists, module: :r_k_d, controller: :artists
      resources :artist_involvements
      resources :attachments
      resources :library_items
    end
    resources :rkd_artists, module: :r_k_d, controller: :artists do
      patch "copy" => "rkd_artists#copy"
    end

    get "works/modified" => "works#modified_index"

    resource :batch, only: [:show, :update, :new, :create]

    get "mobile" => "mobiles#show"
    patch "mobile" => "mobiles#update"

    resources :works do
      resources :attachments
      resources :appraisals
      resources :messages
      resources :library_items
      resources :time_spans
      get "old_data" => "works#show_old_data"
      get "edit_prices" => "works#edit_prices"
      get "location_history" => "works#location_history"
      get "edit_location" => "works#edit_location"
      get "edit_tags" => "works#edit_tags"
      get "edit_photos" => "works#edit_photos"
    end

    get "report" => "report#show"
    get "stats" => "stats#show"
  end
  resources :artists do
    get :collectie_nederland_summary
    patch "collectie_nederland_summary" => "artists#collectie_nederland_summary_update"
    get "combine_prepare" => "artists#combine_prepare"
    patch "combine" => "artists#combine"
    resources :rkd_artists, module: :r_k_d, controller: :artists
    get "old_data" => "artists#show_old_data"

    resources :artist_involvements
  end
  post "/artists/clean" => "artists#clean"

  resources :professional_activities

  get "debug-offline" => "application#debug_offline"

  get "admin", to: Admin::AdminController.action(:index)

  namespace :admin do
    resources :o_auth_group_mappings
  end
  get "sw" => "application#service_worker"
  get "style-guide" => "application#style_guide"
  root "application#home"

end

app/models/attachment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: attachments
#
#  id            :integer          not null, primary key
#  name          :string
#  file          :string
#  visibility    :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  collection_id :integer
#

class Attachment < ApplicationRecord
  belongs_to :collection
  has_and_belongs_to_many :works
  has_and_belongs_to_many :artists

  validates :file, presence: true

  scope :for_roles, ->(roles) { (roles.include?(:admin) || roles.include?(:advisor)) ? where("1 = 1") : where(arel_table[:visibility].matches_any(roles.collect { |role| "%#{role}%" })) }
  scope :for_role, ->(role) { for_roles([role]) }
  scope :for_me, ->(user) { for_roles(user.roles).where(collection_id: user.accessible_collection_ids) }
  scope :without_works, -> { where.missing(:works) }
  scope :without_artists, -> { where.missing(:artists) }

  mount_uploader :file, BasicFileUploader

  def visibility
    read_attribute(:visibility).to_s.split(",")
  end

  def visibility= values
    write_attribute(:visibility, values.compact_blank!.join(","))
  end

  def append_works= works
    self.works = Work.where(id: (works.pluck(:id) + self.works.pluck(:id))).distinct
  end

  def append_artists= artists
    self.artists = Artist.where(id: (artists.pluck(:id) + self.artists.pluck(:id))).distinct
  end

  def file_name
    name? ? name : self[:file]
  end

  def extension
    self[:file].split(".").last
  end

  def export_file_name
    rv = file_name.downcase.gsub(/\s+/, "_").gsub(/[\#%&{}\\<>*?\/$!'":@+`|=,]/, "")
    rv.end_with?(".#{extension}") ? rv : "#{rv}.#{extension}"
  end
end

app/controllers/attachments/zip_response.rb
# frozen_string_literal: true

module Attachments::ZipResponse
  extend ActiveSupport::Concern

  included do
    include ZipKit::RailsStreaming

    def attachments_zip_response
      if can?(:download_attachments, @collection)
        zip_filename = "bijlagen #{@collection.name}.zip"
        headers["Content-Disposition"] = "attachment; filename=\"#{zip_filename}\""

        file_names = {}
        files = []

        @attachments.each do |attachment|
          file_name = attachment.export_file_name

          if file_names.key?(file_name)
            file_parts = file_name.split(".")
            file_extension = file_parts.pop
            file_base = file_parts.join(".")

            file_names[file_name] += 1

            file_name = "#{file_base} (#{file_names[file_name]}).#{file_extension}"
          else
            file_names[file_name] = 1
          end

          files << [attachment.file.path, file_name]

          attachment.artists.each do |artist|
            files << [attachment.file.path, "artists/#{artist.base_file_name}/#{file_name}"]
          end

          attachment.works.each do |work|
            files << [attachment.file.path, "works/#{work.base_file_name}/#{file_name}"]
          end
        end

        zip_kit_stream do |zip|
          files.lazy.each do |file|
            zip.write_stored_file(file[1]) do |sink|
              sink << File.binread(file[0])
            end
          end
        end

      else
        redirect_to collection_path(@collection), alert: "U heeft onvoldoende rechten om te kunnen downloaden"
      end
    end
  end
end

app/controllers/attachments_controller.rb
# frozen_string_literal: true

class AttachmentsController < ApplicationController
  include Attachments::ZipResponse

  before_action :authenticate_qkunst_user!
  before_action :set_subject
  before_action :set_collection

  before_action :set_attachment, only: [:edit, :update, :destroy]

  authorize_resource

  def index
    @attachments = if @subject
      attachment_scope.where(id: @subject.attachments).all
    else
      attachment_scope.where(collection: @collection.expand_with_child_collections).all
    end

    respond_to do |format|
      format.html {}
      format.zip { attachments_zip_response }
    end
  end

  def new
    @attachment = Attachment.new
    @attachment.collection = @collection.base_collection
    @attachment.works << @work if @work
    @attachment.artists << @artist if @artist
    @attachment.visibility = ["facility_manager", "compliance"]
    @attachment.visibility += ["qkunst"] if current_user.registrator?
    @attachments = attachment_scope.where(collection: @collection.expand_with_parent_collections).all
    @attachments -= @subject.attachments if @subject
  end

  def edit
  end

  def create
    @attachment = Attachment.new(attachment_params)
    @attachment.collection = @collection.base_collection

    respond_to do |format|
      if @attachment.save
        if @work
          @attachment.works << @work
          @collection.cache_work_attributes_present!
          @collection.cache_derived_work_attributes_present!
        end
        @attachment.artists << @artist if @artist

        format.html { redirect_to redirect_url, notice: "Attachment toegevoegd" }
        format.json { render :show, status: :created, location: redirect_url }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_content }
      end
    end
  end

  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        @collection.cache_work_attributes_present!
        @collection.cache_derived_work_attributes_present!

        format.html { redirect_to redirect_url, notice: "Attachment bijgewerkt" }
        format.json { render :show, status: :ok, location: redirect_url }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_content }
      end
    end
  end

  def destroy
    if @subject
      @subject.attachments -= [@attachment]
      notice = "Attachment verwijderd bij #{I18n.t(@subject.class.name.downcase, scope: [:activerecord, :models])}"
    else
      notice = "Attachment volledig verwijderd"
      @attachment.destroy
    end
    respond_to do |format|
      format.html { redirect_to redirect_url, notice: notice }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_attachment
    @attachment = attachment_scope.find(params[:id])
  end

  def attachment_scope
    Attachment.where(collection: current_user.accessible_collections).for_me(current_user)
  end

  def set_subject
    if params[:work_id]
      @work = current_user.accessible_works.find(params[:work_id])
    end
    if params[:artist_id]
      @artist = current_user.accessible_artists.find(params[:artist_id])
    end
    @subject = @work || @artist
  end

  def redirect_url
    if @subject
      [@collection, @subject]
    else
      @collection
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attachment_params
    permit = [:name, :file, :file_cache, append_work_ids: [], append_artist_ids: []]

    permit += [visibility: []] if can?(:edit_visibility, @attachment) || !@attachment&.persisted?

    a_params = params.require(:attachment).permit(permit)
    a_params[:append_works] = current_user.accessible_works.where(id: a_params.delete(:append_work_ids))
    a_params[:append_artists] = current_user.accessible_artists.where(id: a_params.delete(:append_artist_ids))
    a_params
  end
end

app/views/attachments/_form.html.erb
<%= simple_form_for([@attachment.collection, @subject, @attachment].compact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :file, required: @attachment.id ? false : true, hint: @attachment.file? ? "Bijlage #{@attachment.name} wordt niet vervangen of verwijderd wanneer er geen nieuw bestand wordt geupload" : "" %>
    <%= f.hidden_field :file_cache %>

    <%= f.input :name %>

    <%= f.input :visibility, collection: translate_form_options((User::ROLES - [:admin, :advisor, :read_only]), scope: [:activerecord, :values, :user, :role]), checked: @attachment.visibility, multiple: true, as: :check_boxes if !@attachment.persisted? || can?(:edit_visibility, @attachment) %>
    <p><small>Met betrekking tot zichtbaarheid: administratoren en adviseurs kunnen altijd álle bijlagen zien.</small></p>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: :button %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<div id="main">
  <h1>Bewerk bijlage</h1>

<%= render 'form', attachment: @attachment %>

</div>

app/views/attachments/index.html.erb
<div id="main">
<h1>Bijlagen <%= (@subject || @collection).name %></h1>
  <nav class="sub-nav bottom-nav hide-for-print" aria-label="Bijlagenacties">
    <ul class="menu right-aligned menu--only-buttons">
      <li><% if @work %>
  <%= link_to 'Bijlage toevoegen', new_collection_work_attachment_path(@collection, @subject), class: 'primary button', data: { open_in_context: true} if can? :create, @subject.attachments.new(collection: @collection) %>
<% elsif @artist %>
  <%= link_to 'Bijlage toevoegen', new_collection_artist_attachment_path(@collection, @subject), class: 'primary button', data: { open_in_context: true} if can? :create, @subject.attachments.new(collection: @collection) %>
<% else %>
  <%= link_to 'Bijlage toevoegen', new_collection_attachment_path(@collection), class: 'primary button', data: { open_in_context: true} if can? :create, @collection.attachments.new %>
<% end %></li>

<% if can?(:download_attachments, @collection) %>
  <li><%= link_to "Download attachments", "#{request.path}.zip", class: "secondary button"%></li>
<% end%>

    </ul>
  </nav>
<% if @collection.name.to_s.match("Provincie Gelderland") && !@subject %><p>Voorgedefinieerde export-functies kunnen hier niet beheerd worden.</p><% end%>
<label>Filter <input type="text" id="generic-table-filter" data-filters="attachments-table"></label>

<table class="sortable" id="attachments-table">
  <thead>
    <tr>
      <th data-filtered-by="generic-table-filter">Naam</th>
      <% unless @work || @artist %>
      <th data-filtered-by="generic-table-filter">Werken</th>
      <th data-filtered-by="generic-table-filter">Vervaardigers</th>
      <% end %>
      <th data-filtered-by="generic-table-filter">Zichtbaar voor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= link_to attachment.file_name, attachment.file.url %></td>
        <% unless @work || @artist %>
        <td><ul><% attachment.works.each do |work| %><li><%= link_to work.stock_number, collection_work_path(work.collection, work)%></li><% end %></ul></td>
        <td><ul><% attachment.artists.each do |artist| %><li><%= link_to artist.name, collection_artist_path(@collection, artist)%></li><% end %></ul></td>
        <% end %>
        <td><%= attachment.visibility.map{|v| I18n.t(v, scope: [:activerecord, :values, :user, :role]) }.to_sentence %></td>
        <td><%= link_to 'Bewerk', edit_attachment_path(attachment) if can? :edit, attachment %></td>
        <td><%= link_to 'Verwijder', [attachment.collection, @subject, attachment].compact, method: :delete, data: { confirm: @subject ? "Weet je zeker dat je de bijlage hier wilt weghalen (de bijlage blijft bij de collectie)?" :"Weet je zeker dat je '#{attachment.file_name}' definitief overal wilt verwijderen?" } if can? :destroy, attachment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @work %>
  <% @custom_reports = @work.custom_reports.to_a %>
  <% if @custom_reports.count > 0 and qkunst_user? %>
  <hr />
    <h3>Rapportages</h3>
    <p>Rapportages worden automatisch aan een werk gekoppeld zodra hiernaar wordt verwezen in de rapportage.</p>
      <%= render partial: 'custom_reports/index' %>
  <% end %>
<% end %>

app/views/attachments/new.html.erb
<div id="main">
  <h1>Voeg bijlage toe</h1>
  <%
  couple = false
  attachment_params = {}
  name = ""
  if @work
    couple = @attachments.any?
    attachment_params = { append_work_ids: [@work.id] }
    name = @work.name
  elsif @artist
    couple = @attachments.any?
    attachment_params = { append_artist_ids: [@artist.id] }
    name = @artist.name
  end

  %>

<% if couple %>
  <p>Bij <%= name %></p>
  <h3>Bestaande bijlage koppelen</h3>
  <label>Filter bijlagen <input type="text" id="generic-table-filter" data-filters="attachments-table"></label>

  <table class="sortable" id="attachments-table">
    <thead>
      <th data-filtered-by="generic-table-filter" class="asc">Naam</th><th>Acties</th></th>
    </thead>
    <tbody>
      <% @attachments.each do |attachment| %>
        <tr><td><%=attachment.name.to_s.gsub(/\_/," ")%></td><td><%=button_to "Koppel", attachment, params: {attachment: attachment_params}, method: :patch, class: [:button, :secondary, :small] %></td></tr>
      <% end %>
      </ul>
    </tbody>
  </table>
  <hr/>
  <h3>Nieuwe bijlage</h3>

<% else %>
    <p>Bij <%= @attachment.collection.name %></p>
<% end %>
    <%= render 'form', attachment: @attachment %>
</div>