config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  get "short_code_resolver/resolve/:collection_code/:work_code" => "short_code_resolver#resolve"
  get "application_status" => "status#application_status"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :custom_report_templates
  get "tags.json" => "application#tags"
  get "geoname_summaries.json" => "application#geoname_summaries"

  resources :reminders
  resources :stages
  get "offline/work_form"

  get "offline/offline"

  get "offline/collections"

  get "offline/collection"

  get "scan" => "scan#show"

  namespace :api do
    namespace :v1 do
      resources :time_spans, only: [:index, :show]
      resources :works, only: [:show]
      resources :work_sets, only: [:show]
      resources :collections, only: [:index, :show] do
        resources :works, only: [:index, :show] do
          resources :work_events, only: [:create]
        end
      end
    end
  end

  resources :messages do
    get "new_reply" => "messages#new"
  end
  devise_for :users, controllers: {
    confirmation: "confirmation",
    registrations: "registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }
  resources :users, only: [:index, :edit, :update, :destroy]
  get "users/oauth"

  resources :conditions
  resources :currencies
  resources :damage_types
  resources :frame_damage_types
  resources :frame_types
  resources :media
  resources :object_categories
  resources :logistical_peculiarities
  resources :placeabilities
  resources :sources
  resources :subsets
  resources :techniques
  resources :themes
  resources :balance_categories
  resources :work_statuses
  resources :work_sets, only: [:show, :index] do
    resources :works, module: :work_sets, only: :destroy # , controller: "WorkSet::WorksController"
  end
  resources :work_set_types

  resources :rkd_artists, module: :r_k_d, controller: :artists do
    patch "copy" => "rkd_artists#copy"
  end

  resources :works do
    resources :attachments
  end

  resources :involvements
  resources :collections do
    get "manage" => "collections#manage"
    get "manage/surface_tool" => "collections#surface_tool"
    resources :contacts
    resources :locations
    resources :users, module: :collection
    resources :labels, module: :collection
    resources :library_items
    resources :time_spans, only: [:index, :show]

    resources :work_sets do
      resources :appraisals
      resources :time_spans
    end

    resources :reminders, path: "manage/reminders"
    resources :themes, path: "manage/themes"
    resources :clusters
    resources :import_collections, path: "manage/import_collections" do
      get "preview" => "import_collections#preview"
      patch "delete_works" => "import_collections#delete_works"
      patch "import_works" => "import_collections#import_works"
    end

    resources :simple_import_collections, path: "manage/simple_import_collections" do
      get "preview" => "simple_import_collections#preview"
      patch "import_works" => "simple_import_collections#import_works"
    end

    resources :owners
    resources :custom_reports, path: "manage/custom_reports"

    resources :attachments
    resources :collections_stages
    resources :messages
    post "refresh_works" => "collections#refresh_works"
    resources :collections do
    end
    resources :batch_photo_uploads do
      post "match_works" => "batch_photo_uploads#match_works"
    end
    resources :artists do
      get :collectie_nederland_summary

      get "combine_prepare" => "artists#combine_prepare"
      patch "combine" => "artists#combine"

      resources :rkd_artists, module: :r_k_d, controller: :artists
      resources :artist_involvements
      resources :attachments
      resources :library_items
    end
    resources :rkd_artists, module: :r_k_d, controller: :artists do
      patch "copy" => "rkd_artists#copy"
    end

    get "works/modified" => "works#modified_index"

    resource :batch, only: [:show, :update, :new, :create]

    get "mobile" => "mobiles#show"
    patch "mobile" => "mobiles#update"

    resources :works do
      resources :attachments
      resources :appraisals
      resources :messages
      resources :library_items
      resources :time_spans
      get "old_data" => "works#show_old_data"
      get "edit_prices" => "works#edit_prices"
      get "location_history" => "works#location_history"
      get "edit_location" => "works#edit_location"
      get "edit_tags" => "works#edit_tags"
      get "edit_photos" => "works#edit_photos"
    end

    get "report" => "report#show"
    get "stats" => "stats#show"
  end
  resources :artists do
    get :collectie_nederland_summary
    patch "collectie_nederland_summary" => "artists#collectie_nederland_summary_update"
    get "combine_prepare" => "artists#combine_prepare"
    patch "combine" => "artists#combine"
    resources :rkd_artists, module: :r_k_d, controller: :artists
    get "old_data" => "artists#show_old_data"

    resources :artist_involvements
  end
  post "/artists/clean" => "artists#clean"

  resources :professional_activities

  get "debug-offline" => "application#debug_offline"

  get "admin", to: Admin::AdminController.action(:index)

  namespace :admin do
    resources :o_auth_group_mappings
  end
  get "sw" => "application#service_worker"
  get "style-guide" => "application#style_guide"
  root "application#home"

end

app/models/stage.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: stages
#
#  id                :integer          not null, primary key
#  name              :string
#  actual_stage_id   :integer
#  previous_stage_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Stage < ApplicationRecord
  belongs_to :previous_stage, primary_key: :id, class_name: "Stage", optional: true
  belongs_to :actual_stage, primary_key: :id, class_name: "Stage", optional: true
  has_many :next_stages, foreign_key: :previous_stage_id, class_name: "Stage"
  has_and_belongs_to_many :collections

  scope :actual_stages, -> { where(actual_stage_id: nil) }

  attr_accessor :enabled, :collection_stage

  def next_stages_actualized
    next_stages.actualize
  end

  def enabled!
    self.enabled = true
  end

  def enabled?
    enabled ? true : false
  end

  def completed?
    collection_stage ? collection_stage.completed? : false
  end

  def completed_at
    collection_stage&.completed_at
  end

  def active?
    collection_stage ? collection_stage.active? : false
  end

  def non_cyclic_graph_from_here(collection = nil)
    collection_stage = collection&.find_state_of_stage(self)
    enabled! if collection_stage || !collection
    self.collection_stage = collection_stage
    graph = [[self]]
    next_stages = next_stages_actualized
    step = 1
    while (next_stages.count > 0) && !next_stages.include?(self)
      stages = next_stages
      next_stages = []
      stages.each do |stage|
        collection_stage = collection&.find_state_of_stage(stage)
        stage.enabled! if collection_stage || !collection
        stage.collection_stage = collection_stage
        branch_index = stages.index(stage)
        if graph[branch_index].nil?
          graph[branch_index] = (step.times.collect { nil } + [stage])
        else
          graph[branch_index] << stage
        end
        next_stages += stage.next_stages_actualized
      end
      next_stages = next_stages.uniq
      step += 1
    end
    graph
  end

  class << self
    def start
      starts.first
    end

    def starts
      where(previous_stage: nil)
    end

    def actualize
      Stage.unscoped.where(id: all.collect { |a| a.actual_stage_id || a.id })
    end
  end
end

app/controllers/stages_controller.rb
# frozen_string_literal: true

class StagesController < ApplicationController
  before_action :authenticate_admin_user!

  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  # GET /stages
  # GET /stages.json
  def index
    # @stages = Stage.all
    # @tree = Stage.first.non_cyclic_graph_from_here
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
    @collection = Collection.new(collections_stages: [CollectionsStage.new(stage: @stage, completed: true)])
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage, notice: "Fase is aangemaakt" }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new }
        format.json { render json: @stage.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to @stage, notice: "Fase is bijgewerkt" }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit }
        format.json { render json: @stage.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to stages_url, notice: "Fase is verwijderd" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stage
    @stage = Stage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stage_params
    params.require(:stage).permit(:name, :actual_stage_id, :previous_stage_id)
  end
end

app/views/stages/_form.html.erb
<%= simple_form_for(@stage) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :actual_stage %>
    <%= f.association :previous_stage %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: :button %>
  </div>
<% end %>

app/views/stages/_stages_graph.html.erb
<% collection ||= nil %>
<% Stage.starts.each do |start| %>
  <% non_cyclic_graph_from_start = start.non_cyclic_graph_from_here(collection) %>
<div class="stages_graph">
  <table class="non_cyclic_graph">
  <% branch_count = non_cyclic_graph_from_start.count %>
  <caption class="sr-only">
      Projectfase
    </caption>
  <thead>
    <tr>
      <% non_cyclic_graph_from_start[0].count.times do |a| %>
        <th>Fase <%= a+1%></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% non_cyclic_graph_from_start.each do |branch| %>
      <tr>
        <% branch.each_with_index do |leaf, index| %>
          <% if leaf %>
            <td class="<%= leaf.enabled? ? 'enabled' : 'disabled' %><%= leaf.completed? ? ' completed' : '' %><%= leaf.active? ? ' active' : '' %>" rowspan="<%=branch_count - non_cyclic_graph_from_start.collect{|a| a[index]}.compact.count + 1%>" title="<%= leaf.completed? ? "Voltooid op #{I18n.l leaf.completed_at.to_date, format: :long}" : "" %>">
              <% if collection and collection.id %>
                <% if leaf.enabled and !leaf.completed? and can?(:update_status, collection) %>
                  <%= button_to(leaf.name, collection_collections_stage_path(collection, leaf.collection_stage), params: {collections_stage: {completed: true}}, method: :patch, data: {confirm: "Weet u zeker dat u dit stadium als voltooid wilt beschouwen?"})%>
                <% else %>
                  <%= leaf.name%>
                <% end %>
              <% else%>
                <%= link_to(leaf.name, leaf) %>
              <% end %>
            </td>
          <% end %>
        <% end%>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>
<% end %>

app/views/stages/edit.html.erb
<h2>Fase bewerken <small>(<%=link_to 'verwijder', stage_path(@stage), method: :delete, data: {confirm: 'Weet u zeker dat u deze fase wilt verwijderen?'}%>)</h2>

<%= render 'form', stage: @stage %>

<%= link_to 'Terug', stages_path %>

app/views/stages/index.html.erb
<h2>Projectfasering</h2>
<p>Projecten doorlopen meerdere fases.</p>
<%= render :partial => 'stages_graph', locals: {collection: nil, action: :link_to} %>

<h3>Lijstweergave</h3>
<ul>
<% Stage.all.each do |stage| %>
<li><%= link_to stage.name, stage %></li>
<% end %>
</ul>
<%= link_to 'Nieuw fase', new_stage_path %>

app/views/stages/new.html.erb
<h2>Nieuw stadium</h2>

<%= render 'form', stage: @stage %>

<%= link_to 'Terug', stages_path %>

app/views/stages/show.html.erb
<h2>Projectfase: <%= @stage.name %></h2>
<%= render :partial => 'stages_graph', locals: {collection: @collection, action: :link_to} %>

<% if @stage.actual_stage %>
<p>Deze fase is slechts een ontvangende fase om ook convergerende flows mogelijk te maken. Ga naar de eigenlijke fase <strong><%= link_to(@stage.actual_stage.name, @stage.actual_stage) %></strong></p>
<% end %>

<% if @stage.previous_stage %>
<p>Voorgaande fase: <strong><%= link_to(@stage.previous_stage.name, @stage.previous_stage) %></strong></p>
<% end %>

<% if @stage.next_stages %>
<p>Volgende fases: <ul><% @stage.next_stages.collect do |nstage| %>
  <li><%= link_to(nstage.name, nstage) %></li>
<% end %>
</ul></p>
<% end %>
<%= link_to 'Bewerk', edit_stage_path(@stage), class: :button %>